# Generated by Django 3.2.6 on 2021-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='main_title',
            field=models.CharField(help_text='Enter main webpage title', max_length=50),
        ),
        migrations.AlterField(
            model_name='configure',
            name='sub_title',
            field=models.CharField(help_text='Write a short description (10 words)', max_length=100),
        ),
    ]
