# Generated by Django 3.2.6 on 2021-08-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20210820_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='main_title',
            field=models.CharField(default='Ana Veljković', help_text='Enter main webpage title', max_length=50),
        ),
    ]
