# Generated by Django 3.2.6 on 2021-08-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_alter_configure_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='sub_title',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor', help_text='Write a short description (10 words)', max_length=100),
        ),
    ]
