# Generated by Django 3.2.6 on 2021-08-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_alter_configure_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='mini_item_descript_1',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.', help_text='Enter description of the first circular item', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_descript_2',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.', help_text='Enter description of the second circular item', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_descript_3',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.', help_text='Enter description of the third circular item', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_title_1',
            field=models.CharField(default='Heading 1', help_text='Enter title of the first circular item', max_length=20),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_title_2',
            field=models.CharField(default='Heading 2', help_text='Enter title of the second circular item', max_length=20),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_title_3',
            field=models.CharField(default='Heading 3', help_text='Enter title of the third circular item', max_length=20),
        ),
    ]
