# Generated by Django 3.2.6 on 2021-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20210820_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='mini_item_descript_1',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the first circular item', max_length=290),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_descript_2',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the second circular item', max_length=290),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_descript_3',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the third circular item', max_length=290),
        ),
    ]
