# Generated by Django 3.1.1 on 2021-08-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20210820_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configure',
        ),
    ]
