# Generated by Django 3.1.1 on 2021-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('life', '0007_delete_configure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Ana Veljković', help_text='Enter main webpage title', max_length=50)),
                ('sub_title', models.CharField(default='Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor', help_text='Write a short description (10 words)', max_length=100)),
                ('mini_item_title_1', models.CharField(default='Heading 1', help_text='Enter title of the first circular item', max_length=20)),
                ('mini_item_descript_1', models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the first circular item', max_length=290)),
                ('mini_item_title_2', models.CharField(default='Heading 2', help_text='Enter title of the second circular item', max_length=20)),
                ('mini_item_descript_2', models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the second circular item', max_length=290)),
                ('mini_item_title_3', models.CharField(default='Heading 3', help_text='Enter title of the third circular item', max_length=20)),
                ('mini_item_descript_3', models.CharField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis en', help_text='Enter description of the third circular item', max_length=290)),
            ],
        ),
    ]
