# Generated by Django 3.1.1 on 2021-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_configure'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='main_image',
            field=models.CharField(default="{% static 'pics/profile_pic.png' %}", help_text='Replace this with the URL of the image', max_length=10000),
        ),
    ]
