# Generated by Django 3.2.6 on 2021-08-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0009_configure_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='main_image',
            field=models.ImageField(default='profile_pic.png', help_text='Please submit a main image', upload_to=''),
        ),
    ]
