# Generated by Django 3.2.6 on 2021-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0010_auto_20210821_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='main_image',
            field=models.ImageField(help_text='Please submit a main image', upload_to='pics/'),
        ),
    ]
