# Generated by Django 3.2.6 on 2021-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0013_auto_20210821_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='slideshow_background_2',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
    ]
