# Generated by Django 3.2.6 on 2021-08-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_configure_slideshow_background_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='block_descritption_1',
            field=models.CharField(default='Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.', help_text='Enter block discription', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_descritption_2',
            field=models.CharField(default='Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.', help_text='Enter block discription', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_descritption_3',
            field=models.CharField(default='Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.', help_text='Enter block discription', max_length=250),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_image_1',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a block image - 500x500px preferably', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_image_2',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a block image - 500x500px preferably', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_image_3',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a block image - 500x500px preferably', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_black_1',
            field=models.CharField(default='First featurette heading.', help_text='Enter black block title', max_length=100),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_black_2',
            field=models.CharField(default="Oh yeah, it's that good.", help_text='Enter black block title', max_length=100),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_black_3',
            field=models.CharField(default='And lastly, this one.', help_text='Enter black block title', max_length=100),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_silver_1',
            field=models.CharField(default="It'll blow your mind.", help_text='Enter silver block title', max_length=100),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_silver_2',
            field=models.CharField(default='See for yourself.', help_text='Enter silver block title', max_length=100),
        ),
        migrations.AddField(
            model_name='configure',
            name='block_title_silver_3',
            field=models.CharField(default='Checkmate.', help_text='Enter silver block title', max_length=100),
        ),
    ]
