# Generated by Django 3.2.6 on 2021-08-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0015_auto_20210821_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='scroll_through_image',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='scroll_through_subtitle',
            field=models.CharField(default='Checkmate.', help_text='Enter scroll subtitle', max_length=300),
        ),
        migrations.AddField(
            model_name='configure',
            name='scroll_through_title',
            field=models.CharField(default='And lastly, this one.', help_text='Enter scroll title', max_length=100),
        ),
    ]
