# Generated by Django 3.2.6 on 2021-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0016_auto_20210821_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='mini_item_image_1',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_image_2',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='configure',
            name='mini_item_image_3',
            field=models.ImageField(default='pics/road.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
    ]
