# Generated by Django 3.2.6 on 2021-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0017_auto_20210821_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='main_image',
            field=models.ImageField(default='pics/profile.png', help_text='Please submit a main image', upload_to='pics/'),
        ),
    ]
