# Generated by Django 3.2.6 on 2021-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0018_alter_configure_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='mini_item_image_1',
            field=models.ImageField(default='pics/question_mark.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_title_1',
            field=models.CharField(default='Life Coaching', help_text='Enter title of the first circular item', max_length=20),
        ),
        migrations.AlterField(
            model_name='configure',
            name='sub_title',
            field=models.CharField(default='Identify, clarify and create a vision for what you want.', help_text='Write a short description (10 words)', max_length=100),
        ),
    ]
