# Generated by Django 3.2.6 on 2021-08-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0019_auto_20210822_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='mini_item_image_2',
            field=models.ImageField(default='pics/public_speaking.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_image_3',
            field=models.ImageField(default='pics/plane.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_title_2',
            field=models.CharField(default='Communication Skills', help_text='Enter title of the second circular item', max_length=20),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_title_3',
            field=models.CharField(default='Expat Support', help_text='Enter title of the third circular item', max_length=20),
        ),
    ]
