# Generated by Django 3.2.6 on 2021-08-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0020_auto_20210822_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='block_image_1',
            field=models.ImageField(default='pics/keyboard.jpg', help_text='Please submit a block image - 500x500px preferably', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='block_title_black_1',
            field=models.CharField(default='Unlock your potential.', help_text='Enter black block title', max_length=100),
        ),
        migrations.AlterField(
            model_name='configure',
            name='block_title_silver_1',
            field=models.CharField(default='And yes you can.', help_text='Enter silver block title', max_length=100),
        ),
    ]
