# Generated by Django 3.2.6 on 2021-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0022_auto_20210822_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='block_title_black_1',
            field=models.CharField(default='Who am I?', help_text='Enter black block title', max_length=100),
        ),
        migrations.AlterField(
            model_name='configure',
            name='block_title_silver_1',
            field=models.CharField(default='A brief overview.', help_text='Enter silver block title', max_length=100),
        ),
        migrations.AlterField(
            model_name='configure',
            name='slideshow_background_2',
            field=models.ImageField(default='pics/sparrows.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='slideshow_subtitle_2',
            field=models.CharField(default='The art of communication is the language of leadership.', help_text='Slideshow Subheading description', max_length=100),
        ),
        migrations.AlterField(
            model_name='configure',
            name='slideshow_title_2',
            field=models.CharField(default='- James Humes', help_text='Slideshow Heading description', max_length=50),
        ),
    ]
