# Generated by Django 3.2.6 on 2021-08-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0023_auto_20210822_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='slideshow_background_1',
            field=models.ImageField(default='pics/success.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
    ]
