# Generated by Django 3.2.6 on 2021-08-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0024_alter_configure_slideshow_background_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='slideshow_background_3',
            field=models.ImageField(default='pics/hands.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='slideshow_subtitle_3',
            field=models.CharField(default="Make a big life change is pretty scarry. But know what's even scarier? Regret.", help_text='Slideshow Subheading description', max_length=100),
        ),
        migrations.AlterField(
            model_name='configure',
            name='slideshow_title_3',
            field=models.CharField(default='- Zig Ziglar', help_text='Slideshow Heading description', max_length=50),
        ),
    ]
