# Generated by Django 3.2.6 on 2021-08-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0026_auto_20210822_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='block_image_1',
            field=models.ImageField(default='pics/me.jpg', help_text='Please submit a block image - 500x500px preferably', upload_to='pics/'),
        ),
    ]
