# Generated by Django 3.2.6 on 2021-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0028_auto_20210822_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='scroll_through_image',
            field=models.ImageField(default='pics/tree.jpg', help_text='Please submit a darkened slideshow background - 1920x1080 minimum', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='scroll_through_subtitle',
            field=models.CharField(default="It's never too late.", help_text='Enter scroll subtitle', max_length=300),
        ),
        migrations.AlterField(
            model_name='configure',
            name='scroll_through_title',
            field=models.CharField(default='Find peace and equilibrium.', help_text='Enter scroll title', max_length=100),
        ),
    ]
