# Generated by Django 3.2.6 on 2021-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0029_auto_20210822_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='mini_item_image_1',
            field=models.ImageField(default='pics/sunflower.jpg', help_text='Please submit a mini image', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='mini_item_title_1',
            field=models.CharField(default='Personal Growth', help_text='Enter title of the first circular item', max_length=20),
        ),
    ]
