# Generated by Django 3.2.6 on 2021-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0030_auto_20210822_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
