# Generated by Django 3.2.6 on 2021-08-22 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0031_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='slideshow_banner_1',
            field=models.CharField(default='Personal Growth', help_text='Slideshow Left Banner', max_length=20),
        ),
        migrations.AddField(
            model_name='configure',
            name='slideshow_banner_2',
            field=models.CharField(default='Communication Skills', help_text='Slideshow Left Banner', max_length=20),
        ),
        migrations.AddField(
            model_name='configure',
            name='slideshow_banner_3',
            field=models.CharField(default='Expat Support', help_text='Slideshow Left Banner', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
