# Generated by Django 3.2.5 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0032_auto_20210822_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='configure',
            name='main_banner',
            field=models.CharField(default='Life Coaching', help_text='Enter the main banner text', max_length=20),
        ),
    ]
